### ISSUE TITLE
New color scheme seems a bit...washed off?

### ISSUE THREAD

**Issue by System-x64** [hyprwm/hyprland-wiki#29]
idk maybe I am being stereotypical but don't y'all think the newer theme specially the background color just looks like someone turned the contrast slider to -50 , i mean we all programmers can agree, we like dark mode that's actually dark (like material oceanic)   and ig the majority of peeps using hyprland are...computer related by any sort? Idk this is still just my personal opinion , i'm just here to look for your views
![screenshot_20221014_231503](https://user-images.githubusercontent.com/90208727/195910537-8a716c82-652b-4674-921c-8aceeb1aa775.png)

**Comment by System-x64** [comment]
oh sry, here's a 100% opacity look
![screenshot_20221014_232541](https://user-images.githubusercontent.com/90208727/195910844-218d4898-98ff-44d4-89a4-5144404b5d82.png)

**Comment by fufexan** [comment]
Check if your Dark Reader is interfering. It looks like it always has on my machine.
![image](https://user-images.githubusercontent.com/36706276/195911383-370f05fd-206f-4b1e-a34e-cb57e706b0ed.png)

**Comment by System-x64** [comment]
![screenshot_20221014_232949](https://user-images.githubusercontent.com/90208727/195911548-74ff8776-c4ab-46e2-8355-657285d8d805.png)
wait wut, but my dark reader is off, i even check on my iphone, its still showing the washed off scheme

**Comment by System-x64** [comment]
> ![screenshot_20221014_232949](https://user-images.githubusercontent.com/90208727/195911548-74ff8776-c4ab-46e2-8355-657285d8d805.png) wait wut, but my dark reader is off, i even check on my iphone (safari), its still showing the washed off scheme

**Comment by System-x64** [comment]
![image](https://user-images.githubusercontent.com/90208727/195912082-6fcfa4fa-b0bd-45df-a399-c49f022b0afd.png)

**Comment by vaxerski** [comment]
it is your fault @fufexan and I am expecting a fix. You were the one to "just remove custom.css who needs this".

**Comment by vaxerski** [comment]
after that everything went to shit.

**Comment by fufexan** [comment]
It's still in there, just linked. Shouldn't change things unless Hugo doesn't follow symlinks.

But yeah, I'll fix it.

**Comment by vaxerski** [comment]
should be fixed cuz @fufexan is a lazy bum.

@System-x64 fyi: it's not *new*, it's *default* lol

**Comment by System-x64** [comment]
> should be fixed by me cuz @fufexan is a lazy bum.
> 
> 
> 
> @System-x64 fyi: it's not *new*, it's *default* lol

Apparently, nope it's still the same ![image](https://user-images.githubusercontent.com/90208727/195967269-c29807b0-bcad-4598-8377-73a946a7dc15.png) (u have fixed or u will fix?)

**Comment by vaxerski** [comment]
delete cache and try again

**Comment by System-x64** [comment]
doesn't help

**Comment by System-x64** [comment]
F now i have to sign in to each of my accounts again,deleted the entire browser cache instead of site :P

**Comment by vaxerski** [comment]
you deleted *data* and not *cache* then

**Comment by vaxerski** [comment]
shit, right. It reverts on every rebuild.

**Comment by vaxerski** [comment]
@fufexan for fucks sake you broke the entire thing even reverting your shitty ass commit wont fix it now idiot

**Comment by System-x64** [comment]
...

**Comment by vaxerski** [comment]
check now
I think I managed to fix it

**Comment by System-x64** [comment]
![image](https://user-images.githubusercontent.com/90208727/195988818-1d7b9b38-dd62-40bd-a6c9-bac76e695658.png)
Yes, finally! 🥹

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/195988857-36719d85-3b45-4203-888d-91bb4da33fdf.png)

it's all because of this guy

**Comment by System-x64** [comment]
xD
